# Full reference: https://docs.airplane.dev/tasks/task-definition

slug: demo_list_account_users
name: "[DEMO] List Account Users"
description: List users for an account

parameters:
  - slug: account_id
    name: Account ID
    type: integer

sql:
  resource: "demo_db"
  entrypoint: list_account_users.sql
  queryArgs:
    account_id: "{{params.account_id}}"
